(TeX-add-style-hook "dissertation"
 (lambda ()
    (TeX-run-style-hooks
     "xcolor"
     "usenames"
     "dvipsnames"
     "svgnames"
     "table"
     "color"
     "listings"
     "hyperref"
     "graphicx"
     "setspace"
     "geometry"
     "latex2e"
     "rep12"
     "report"
     "12pt"
     "a4paper"
     "Acknowledgements"
     "Abstract"
     "Introduction"
     "Literature_Review"
     "Design"
     "Implementation"
     "Results"
     "Conclusion"
     "Bib"
     "Appendix")))

